routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

//New Password From Direct Login Luma account
//$this->get('login/password/directlogin/new', 'Auth\DirectLoginController@showDirectLoginPasswordForm')->name('directlogin.password');
Route::post('directlogin/account/new', ['uses' => 'Auth\DirectLoginController@createAccount', 'as' => 'directlogin.password']);

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    
});

/*
** AirAsia Orders
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'airasia', 'as' => 'aa_orders.'], function () {
   Route::get('/orders',['as'=>'index','uses'=>'Admin\Reports\AirasiaOrderController@index']);
   Route::get('/orders/{id}/paxslip',['as'=>'orders.paxslip','uses'=>'Admin\Reports\AirasiaOrderController@paxSlip']);
   Route::post('orders/upload',['uses'=>'Admin\Reports\AirasiaOrderController@upload']);
});

/*
** Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'report', 'as' => 'report.'], function () {
        Route::get('warehouse',['as'=> 'warehouse', 'uses' => 'Admin\Reports\WarehouseReportsController@index']);
        Route::get('warehouse/export',['as'=> 'export', 'uses' => 'Admin\Reports\WarehouseReportsController@exportReportCSV']);
        Route::get('warehouse/order/{id}',['as'=> 'warehouse.detail', 'uses' => 'Admin\Reports\WarehouseReportsController@orderDetail']);
        Route::get('warehouse/order/{id}/paxslip',['as'=> 'warehouse.paxslip', 'uses' => 'Admin\Reports\WarehouseReportsController@paxSlip']);

        Route::post('warehouse/order/update/{id}',['as' => 'warehouse.update-status', 'uses' => 'Admin\Reports\WarehouseReportsController@updateStatus']);
    });

/*
** New Warehouse Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'wreport2', 'as' => 'wreport2.'], function () {

   Route::get('warehouse2',['as'=> 'warehouse', 'uses' => 'Admin\Reports\WarehouseReports2Controller@index']);
   Route::get('warehouse2/export',['as'=> 'export', 'uses' => 'Admin\Reports\WarehouseReports2Controller@exportReport']);
   Route::get('warehouse2/order/{seller_id}/view/{order_id}',['as'=> 'warehouse.detail', 'uses' => 'Admin\Reports\WarehouseReports2Controller@orderDetail']);
   Route::get('warehouse2/order/{seller_id}/paxslip/{order_id}',['as'=> 'warehouse.paxslip', 'uses' => 'Admin\Reports\WarehouseReports2Controller@paxSlip']);
   Route::post('warehouse2/order/{order_id}/updatemagento/{seller_ids}',['as' => 'warehouse.magento-order-update-status', 'uses' => 'Admin\Reports\WarehouseReports2Controller@updateAdminStatus']);
   Route::post('warehouse2/order/{order_id}/updateseller/{seller_id}',['as' => 'warehouse.seller-order-update-status', 'uses' => 'Admin\Reports\WarehouseReports2Controller@updateSellerOrderStatus']);
   Route::get('warehouse2/order/{seller_id}/invoice/{increment_id}/{order_id}',['as'=> 'warehouse.invoice', 'uses' => 'Admin\Reports\WarehouseReports2Controller@generateInvoice']);


});

/*
** Custom Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'customreport', 'as' => 'customreport.'], function () {
   Route::get('/',['as'=> 'index', 'uses' => 'Admin\Reports\CustomReportController@index']);
   Route::get('/exportall',['as'=> 'exportAll', 'uses' => 'Admin\Reports\CustomReportController@exportAllCustomReports']);
   Route::get('/order/export',['as'=> 'export', 'uses' => 'Admin\Reports\CustomReportController@exportCustomReportExcel']);
   Route::get('/order/{id}',['as'=> 'detail', 'uses' => 'Admin\Reports\CustomReportController@orderDetail']);
   Route::get('/order/{id}/paxslip',['as'=> 'paxslip', 'uses' => 'Admin\Reports\CustomReportController@paxSlip']);
   Route::post('/order/update/{id}',['as' => 'update-status', 'uses' => 'Admin\Reports\CustomReportController@updateStatus']);

});


//Seller Portal

// Change Password Routes...
$this->get('seller/change_password', 'Seller\Auth\ChangePasswordController@showChangePasswordForm')->name('seller-change_password');
$this->patch('seller/change_password', 'Seller\Auth\ChangePasswordController@changePassword')->name('seller.change_password');

// Password Reset Routes...
$this->get('seller/password/reset', 'Seller\Auth\ForgotPasswordController@showLinkRequestForm')->name('seller-password-reset-link');
$this->post('seller/password/email', 'Seller\Auth\ForgotPasswordController@sendResetLinkEmail')->name('seller-password-reset-email');
$this->get('seller/password/reset/{token}', 'Seller\Auth\ResetPasswordController@showResetForm')->name('password-reset-form');
$this->post('seller/password/reset', 'Seller\Auth\ResetPasswordController@reset')->name('seller-password-reset');

$this->post('seller/logout', 'Seller\Auth\SellerLoginController@logout')->name('seller.post-logout');
$this->get('seller/login', 'Seller\Auth\SellerLoginController@showLoginForm')->name('seller.login');;
$this->post('seller/login','Seller\Auth\SellerLoginController@login')->name('seller.post-login');

Route::group(['middleware' => ['seller'], 'prefix' => 'seller', 'as' => 'seller.'], function () {
    
   
    Route::get('/',['as' => 'index','uses' => 'Seller\Auth\HomeSellerController@index']);
    Route::get('/home',['as' => 'home','uses' => 'Seller\Auth\HomeSellerController@index']);
   
    Route::get('/orders',['as'=> 'orders-index', 'uses' => 'Seller\Reports\SellerSalesReportController@index']);
    Route::get('/order/{orderid}/{sellerid}',['as'=> 'order-detail', 'uses' => 'Seller\Reports\SellerSalesReportController@orderDetail']);

    Route::post('/order/{orderid}/{sellerid}/status/{status}',['as'=> 'update-order-status', 'uses' => 'Seller\Reports\SellerSalesReportController@updateOrderStatus']);
    Route::post('/order/itemstatus',['as'=> 'update-item-status', 'uses' => 'Seller\Reports\SellerSalesReportController@updateItemStatus']);
    Route::get('/sellerorders/export',['as'=> 'export', 'uses' => 'Seller\Reports\SellerSalesReportController@exportReport']);
    
    Route::resource('permissions', 'Seller\AccountManagement\SellerPermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerPermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Seller\AccountManagement\SellerRolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerRolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Seller\AccountManagement\SellerUsersController');
    Route::post('users_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerUsersController@massDestroy', 'as' => 'users.mass_destroy']);

});

/*
** Agent
*/
Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::get('login',['as' => 'login','uses' => 'Agent\AgentLoginController@showLoginForm']);
    Route::post('login',['as' => 'post-login','uses' => 'Agent\AgentLoginController@agentLogin']);
    Route::get('logout',['as' => 'post-logout','uses' => 'Agent\AgentLoginController@agentLogout']);
});
Route::group(['middleware' => ['agent'],'prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::get('/home', 'Agent\HomeAgentController@index');
    Route::get('report',['as'=> 'report', 'uses' => 'Agent\AgentReportsController@index']);
    Route::get('report/export',['as'=> 'export', 'uses' => 'Agent\AgentReportsController@exportReportCSV']);
    Route::get('report/order/{id}',['as'=> 'report.detail', 'uses' => 'Agent\AgentReportsController@orderDetail']);
    Route::get('report/order/{id}/paxslip',['as'=> 'report.paxslip', 'uses' => 'Agent\AgentReportsController@paxSlip']);

    Route::get('choose-update','Agent\AgentReportsController@getChooseUpdate');
    Route::get('change-pnr/{pnr}','Agent\AgentReportsController@getChangePnr');
    Route::get('change-flight/{pnr}','Agent\AgentReportsController@getFlight');
    Route::get('change-pax','Agent\AgentReportsController@getChangePax');
    Route::get('change-status','Agent\AgentReportsController@getChangeStatus');
    Route::get('/agentid','Agent\UserAgentController@index');
    Route::get('report/order/{id}',['as'=> 'report.detail', 'uses' => 'Agent\AgentReportsController@orderDetail']);
    Route::get('report/pnr/{pnr}',['as'=> 'report.pnr', 'uses' => 'Agent\AgentReportsController@apiGetBooking']);

app/Http/Controllers/Admin/PermissionsController.php
<?php

namespace App\Http\Controllers\Admin;

use Spatie\Permission\Models\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StorePermissionsRequest;
use App\Http\Requests\Admin\UpdatePermissionsRequest;

class PermissionsController extends Controller
{

    private $guard_name = 'web';

    /**
     * Display a listing of Permission.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('manage_accounts')) {
            return redirect()->to('/');
        }

        $permissions = Permission::where('guard_name',$this->guard_name)->get();

        return view('admin.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating new Permission.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('manage_accounts')) {
            return redirect()->to('/');
        }
        return view('admin.permissions.create');
    }

    /**
     * Store a newly created Permission in storage.
     *
     * @param  \App\Http\Requests\StorePermissionsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePermissionsRequest $request)
    {
        if (! Gate::allows('manage_accounts')) {
            return abort(404);
        }
        Permission::create($request->all());

        return redirect()->route('admin.permissions.index');
    }


    /**
     * Show the form for editing Permission.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('manage_accounts')) {
            return redirect()->to('/');
        }
        $permission = Permission::findOrFail($id);

        return view('admin.permissions.edit', compact('permission'));
    }

    /**
     * Update Permission in storage.
     *
     * @param  \App\Http\Requests\UpdatePermissionsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePermissionsRequest $request, $id)
    {
        if (! Gate::allows('manage_accounts')) {
            return abort(404);
        }
        $permission = Permission::findOrFail($id);
        $permission->update($request->all());

        return redirect()->route('admin.permissions.index');
    }


    /**
     * Remove Permission from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('manage_accounts')) {
            return abort(404);
        }
        $permission = Permission::findOrFail($id);
        $permission->delete();

        return redirect()->route('admin.permissions.index');
    }

    /**
     * Delete all selected Permission at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('manage_accounts')) {
            return abort(404);
        }
        if ($request->input('ids')) {
            $entries = Permission::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

app/Http/Controllers/Seller/AccountManagement/SellerPermissionsController.php
<?php

namespace App\Http\Controllers\Seller\AccountManagement;

use Spatie\Permission\Models\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StorePermissionsRequest;
use App\Http\Requests\Admin\UpdatePermissionsRequest;
use Auth;

class SellerPermissionsController extends Controller
{
    /**
     * Display a listing of Permission.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (! Gate::allows('manage_accounts')) {
            return redirect()->to('/seller');
        }

        $permissions = Permission::where('guard_name','seller')->get();

        return view('seller.account-management.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating new Permission.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('manage_accounts')) {
           return redirect()->to('/seller');
        }
        return view('seller.account-management.permissions.create');
    }

    /**
     * Store a newly created Permission in storage.
     *
     * @param  \App\Http\Requests\StorePermissionsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePermissionsRequest $request)
    {
        if (! Gate::allows('manage_accounts')) {
            return abort(401);
        }
        Permission::create($request->all());

        return redirect()->route('seller.permissions.index');
    }


    /**
     * Show the form for editing Permission.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('manage_accounts')) {
            return redirect()->to('/seller');
        }
        $permission = Permission::findOrFail($id);

        return view('seller.account-management.permissions.edit', compact('permission'));
    }

    /**
     * Update Permission in storage.
     *
     * @param  \App\Http\Requests\UpdatePermissionsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePermissionsRequest $request, $id)
    {
        if (! Gate::allows('manage_accounts')) {
             return abort(401);
        }
        $permission = Permission::findOrFail($id);
        $permission->update($request->all());

        return redirect()->route('seller.permissions.index');
    }


    /**
     * Remove Permission from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('manage_accounts')) {
            return redirect()->to('/seller');
        }
        $permission = Permission::findOrFail($id);
        $permission->delete();

        return redirect()->route('seller.permissions.index');
    }

    /**
     * Delete all selected Permission at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('manage_accounts')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Permission::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/seller/account-management/permissions/create.blade.php
@extends('seller.layouts.app-seller')

@section('content')
    <h3 class="page-title">@lang('global.permissions.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['seller.permissions.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/seller/account-management/permissions/edit.blade.php
@extends('seller.layouts.app-seller')

@section('content')
    <h3 class="page-title">@lang('global.permissions.title')</h3>
    
    {!! Form::model($permission, ['method' => 'PUT', 'route' => ['seller.permissions.update', $permission->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('title'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/seller/account-management/permissions/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('seller.layouts.app-seller')

@section('content')
    <h3 class="page-title">@lang('global.permissions.title')</h3>
    <p>
        <a href="{{ route('seller.permissions.create') }}" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> @lang('global.app_add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($permissions) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                         <!--<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>-->
                        <th>@lang('global.permissions.fields.name')</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($permissions) > 0)
                        @foreach ($permissions as $permission)
                            <tr data-entry-id="{{ $permission->id }}">
                                 <!--<td></td>-->
                                <td>{{ $permission->name }}</td>
                                <td>
                                    <a href="{{ route('seller.permissions.edit',[$permission->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['seller.permissions.destroy', $permission->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="3">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        window.route_mass_crud_entries_destroy = '{{ route('seller.permissions.mass_destroy') }}';
    </script>
@endsection