routes/web.php
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

//New Password From Direct Login Luma account
//$this->get('login/password/directlogin/new', 'Auth\DirectLoginController@showDirectLoginPasswordForm')->name('directlogin.password');
Route::post('directlogin/account/new', ['uses' => 'Auth\DirectLoginController@createAccount', 'as' => 'directlogin.password']);

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    
});

/*
** AirAsia Orders
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'airasia', 'as' => 'aa_orders.'], function () {
   Route::get('/orders',['as'=>'index','uses'=>'Admin\Reports\AirasiaOrderController@index']);
   Route::get('/orders/{id}/paxslip',['as'=>'orders.paxslip','uses'=>'Admin\Reports\AirasiaOrderController@paxSlip']);
   Route::post('orders/upload',['uses'=>'Admin\Reports\AirasiaOrderController@upload']);
});

/*
** Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'report', 'as' => 'report.'], function () {
        Route::get('warehouse',['as'=> 'warehouse', 'uses' => 'Admin\Reports\WarehouseReportsController@index']);
        Route::get('warehouse/export',['as'=> 'export', 'uses' => 'Admin\Reports\WarehouseReportsController@exportReportCSV']);
        Route::get('warehouse/order/{id}',['as'=> 'warehouse.detail', 'uses' => 'Admin\Reports\WarehouseReportsController@orderDetail']);
        Route::get('warehouse/order/{id}/paxslip',['as'=> 'warehouse.paxslip', 'uses' => 'Admin\Reports\WarehouseReportsController@paxSlip']);

        Route::post('warehouse/order/update/{id}',['as' => 'warehouse.update-status', 'uses' => 'Admin\Reports\WarehouseReportsController@updateStatus']);
    });

/*
** New Warehouse Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'wreport2', 'as' => 'wreport2.'], function () {

   Route::get('warehouse2',['as'=> 'warehouse', 'uses' => 'Admin\Reports\WarehouseReports2Controller@index']);
   Route::get('warehouse2/export',['as'=> 'export', 'uses' => 'Admin\Reports\WarehouseReports2Controller@exportReport']);
   Route::get('warehouse2/order/{seller_id}/view/{order_id}',['as'=> 'warehouse.detail', 'uses' => 'Admin\Reports\WarehouseReports2Controller@orderDetail']);
   Route::get('warehouse2/order/{seller_id}/paxslip/{order_id}',['as'=> 'warehouse.paxslip', 'uses' => 'Admin\Reports\WarehouseReports2Controller@paxSlip']);
   Route::post('warehouse2/order/{order_id}/updatemagento/{seller_ids}',['as' => 'warehouse.magento-order-update-status', 'uses' => 'Admin\Reports\WarehouseReports2Controller@updateAdminStatus']);
   Route::post('warehouse2/order/{order_id}/updateseller/{seller_id}',['as' => 'warehouse.seller-order-update-status', 'uses' => 'Admin\Reports\WarehouseReports2Controller@updateSellerOrderStatus']);
   Route::get('warehouse2/order/{seller_id}/invoice/{increment_id}/{order_id}',['as'=> 'warehouse.invoice', 'uses' => 'Admin\Reports\WarehouseReports2Controller@generateInvoice']);


});

/*
** Custom Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'customreport', 'as' => 'customreport.'], function () {
   Route::get('/',['as'=> 'index', 'uses' => 'Admin\Reports\CustomReportController@index']);
   Route::get('/exportall',['as'=> 'exportAll', 'uses' => 'Admin\Reports\CustomReportController@exportAllCustomReports']);
   Route::get('/order/export',['as'=> 'export', 'uses' => 'Admin\Reports\CustomReportController@exportCustomReportExcel']);
   Route::get('/order/{id}',['as'=> 'detail', 'uses' => 'Admin\Reports\CustomReportController@orderDetail']);
   Route::get('/order/{id}/paxslip',['as'=> 'paxslip', 'uses' => 'Admin\Reports\CustomReportController@paxSlip']);
   Route::post('/order/update/{id}',['as' => 'update-status', 'uses' => 'Admin\Reports\CustomReportController@updateStatus']);

});


//Seller Portal

// Change Password Routes...
$this->get('seller/change_password', 'Seller\Auth\ChangePasswordController@showChangePasswordForm')->name('seller-change_password');
$this->patch('seller/change_password', 'Seller\Auth\ChangePasswordController@changePassword')->name('seller.change_password');

// Password Reset Routes...
$this->get('seller/password/reset', 'Seller\Auth\ForgotPasswordController@showLinkRequestForm')->name('seller-password-reset-link');
$this->post('seller/password/email', 'Seller\Auth\ForgotPasswordController@sendResetLinkEmail')->name('seller-password-reset-email');
$this->get('seller/password/reset/{token}', 'Seller\Auth\ResetPasswordController@showResetForm')->name('password-reset-form');
$this->post('seller/password/reset', 'Seller\Auth\ResetPasswordController@reset')->name('seller-password-reset');

$this->post('seller/logout', 'Seller\Auth\SellerLoginController@logout')->name('seller.post-logout');
$this->get('seller/login', 'Seller\Auth\SellerLoginController@showLoginForm')->name('seller.login');;
$this->post('seller/login','Seller\Auth\SellerLoginController@login')->name('seller.post-login');

Route::group(['middleware' => ['seller'], 'prefix' => 'seller', 'as' => 'seller.'], function () {
    
   
    Route::get('/',['as' => 'index','uses' => 'Seller\Auth\HomeSellerController@index']);
    Route::get('/home',['as' => 'home','uses' => 'Seller\Auth\HomeSellerController@index']);
   
    Route::get('/orders',['as'=> 'orders-index', 'uses' => 'Seller\Reports\SellerSalesReportController@index']);
    Route::get('/order/{orderid}/{sellerid}',['as'=> 'order-detail', 'uses' => 'Seller\Reports\SellerSalesReportController@orderDetail']);

    Route::post('/order/{orderid}/{sellerid}/status/{status}',['as'=> 'update-order-status', 'uses' => 'Seller\Reports\SellerSalesReportController@updateOrderStatus']);
    Route::post('/order/itemstatus',['as'=> 'update-item-status', 'uses' => 'Seller\Reports\SellerSalesReportController@updateItemStatus']);
    Route::get('/sellerorders/export',['as'=> 'export', 'uses' => 'Seller\Reports\SellerSalesReportController@exportReport']);
    
    Route::resource('permissions', 'Seller\AccountManagement\SellerPermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerPermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Seller\AccountManagement\SellerRolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerRolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Seller\AccountManagement\SellerUsersController');
    Route::post('users_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerUsersController@massDestroy', 'as' => 'users.mass_destroy']);

});

/*
** Agent
*/
Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::get('login',['as' => 'login','uses' => 'Agent\AgentLoginController@showLoginForm']);
    Route::post('login',['as' => 'post-login','uses' => 'Agent\AgentLoginController@agentLogin']);
    Route::get('logout',['as' => 'post-logout','uses' => 'Agent\AgentLoginController@agentLogout']);
});
Route::group(['middleware' => ['agent'],'prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::get('/home', 'Agent\HomeAgentController@index');
    Route::get('report',['as'=> 'report', 'uses' => 'Agent\AgentReportsController@index']);
    Route::get('report/export',['as'=> 'export', 'uses' => 'Agent\AgentReportsController@exportReportCSV']);
    Route::get('report/order/{id}',['as'=> 'report.detail', 'uses' => 'Agent\AgentReportsController@orderDetail']);
    Route::get('report/order/{id}/paxslip',['as'=> 'report.paxslip', 'uses' => 'Agent\AgentReportsController@paxSlip']);

    Route::get('choose-update','Agent\AgentReportsController@getChooseUpdate');
    Route::get('change-pnr/{pnr}','Agent\AgentReportsController@getChangePnr');
    Route::get('change-flight/{pnr}','Agent\AgentReportsController@getFlight');
    Route::get('change-pax','Agent\AgentReportsController@getChangePax');
    Route::get('change-status','Agent\AgentReportsController@getChangeStatus');
    Route::get('/agentid','Agent\UserAgentController@index');
    Route::get('report/order/{id}',['as'=> 'report.detail', 'uses' => 'Agent\AgentReportsController@orderDetail']);
    Route::get('report/pnr/{pnr}',['as'=> 'report.pnr', 'uses' => 'Agent\AgentReportsController@apiGetBooking']);

    Route::get('report/update/pnr/{pnr}/{id}',['as' => 'update.pnr','uses' => 'Agent\AgentReportsController@getUpdateBooking']);

    Route::post('report/order/update-flight/{id}',['as' => 'report.update-flight', 'uses' => 'Agent\AgentReportsController@updateFlight']);
    Route::post('report/order/update-pax/{id}',['as' => 'report.update-pax', 'uses' => 'Agent\AgentReportsController@updatePax']);
    Route::post('report/order/update-pnr/{id}',['as' => 'report.update-pnr', 'uses' => 'Agent\AgentReportsController@updatePnr']);
    Route::post('report/order/update/{id}',['as' => 'report.update-status', 'uses' => 'Agent\AgentReportsController@updateStatus']);
});

/*
** Agent Reports 2
*/

app/Http/Controllers/Agent/AgentLoginController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use GuzzleHttp\Client;
use Session;
use Illuminate\Session\Store;
use Illuminate\Support\Facades\Hash;

class AgentLoginController extends Controller
{
	public function __construct(Store $session){
        $this->session = $session;
    }

	public function showLoginForm(){
		if(Session::has('AgentSession')) {
            return redirect()->to('agent/home');
        } else {
        	Session::flush();
            return view('agent.auth.login');
        }	
		
	}

	public function agentLogin(Request $request) {

		if(config('agentConfig.agent_admin_authorized')->contains([$request->input('agent_name'),$request->input('password')])){

			$result = Hash::make(str_random(8));

			$this->session->put('AgentSession', $result);
			$this->session->put('AgentName', $request->input('agent_name'));
			$this->session->put('AgentType', 'Agent_Super_Admin');

		} else {
			try {
				$success = true;
				$message = 'Found matching user';
				$client = new Client();

				$method = 'GET';

			
				$domain	= env('NAVITAIRE_DOMAIN');
				$api	= env('NAVITAIRE_GETSESSION');

				/* params request */

				$res = $client->request($method, $domain.$api, [
					'headers' => [
						'domainCode'	=> $request->input('type'),
						'agentName'		=> $request->input('agent_name'),
						'agentPassword' => $request->input('password'),
						'Authorization' => 'Bearer '.env('NAVITAIRE_TOKEN')	
					]
				]);

				$result = $res->getBody()->getContents();
				$status_code = 200;
				$this->session->put('AgentSession', $result);
				$this->session->put('AgentName', $request->input('agent_name'));
				$this->session->put('AgentType', $request->input('type'));

				$agent_name = Session::has('AgentName') ? Session::get('AgentName') : '';
				$this->session->put('AgentID', $this->getSessionUserID($agent_name));

			}catch(\GuzzleHttp\Exception\ClientException $e) {
				$status_code = $e->getResponse()->getStatusCode();
				$success = false;
				if($status_code == 422){
					$message = 'Please complete all required fields';
				}
				$this->session->put('error','Please complete all required fields');
				$result = [];

			}catch(\GuzzleHttp\Exception\ConnectException $e) {
				$success = false;
				$message = 'We are sorry to inform that server is currently offline';
				$this->session->put('error',$message);
				$result = [];
			}catch(\GuzzleHttp\Exception\ServerException $e) {
				$success = false;
				$message = 'We are sorry to inform that server is currently encountered a problem';
				$this->session->put('error',$message);
				$result = [];
			}

		}

		if(empty($result)){
				//$this->session->put('error','Username or password invalid. Please try again');
				Session::put('error', 'Username or password invalid. Please try again');
				return redirect()->back();
		} else {
			if($this->session->has('AgentSession')) {
		            return redirect()->to('agent/home');
		    } else {
		            //$this->session->flush();
		        //$this->session->put('error','Username or password invalid. Please try again');
		        Session::put('error', 'Username or password invalid. Please try again');
		        return redirect()->to('/agent/login')->with('error', 'Username or password invalid. Please try again');
		    }
		}
		

	}

	public function agentLogout(Request $request) {
		$this->session->flush();
		return redirect()->to('agent/login');
	}

	public function getSessionUserID($agent_name) {
		try {
            $success = true;
            $message = 'Found matching user';
            $client = new Client();

            $method = 'GET';

            $domain	= env('NEW_ROKKISHOP_DOMAIN');
            $api    = env('NEW_API_CUSTOMER_SEARCH');

            /* params request */
            $params = '?searchCriteria[filterGroups][0][filters][0][field]=agent_name&searchCriteria[filterGroups][0][filters][0][value]='.$agent_name;

            //echo $domain.$api.$params;

            $token = env('NEW_API_TOKEN');
            $res = $client->request($method, $domain.$api.$params, [
                'headers' => [
                    'Authorization'      => 'Bearer '.$token
                ]
            ]);

            $result = json_decode($res->getBody());
            $status_code = 200;

        }catch(\GuzzleHttp\Exception\ClientException $e) {
            $status_code = $e->getResponse()->getStatusCode();
            $success = false;
            if($status_code == 422){
                $message = 'Please complete all required fields';
            }
            $result = [];

        }catch(\GuzzleHttp\Exception\ConnectException $e) {
            $success = false;
            $message = 'We are sorry to inform that server is currently offline';
            $result = [];
        }catch(\GuzzleHttp\Exception\ServerException $e) {
            $success = false;
            $message = 'We are sorry to inform that server is currently encountered a problem';
            $result = [];
        }

        
        if(!empty($result)){
            return $this->getAgentId($result);
        }
	}

	public function getAgentId($result) {

        if (is_array($result) || is_object($result))
        {
            foreach($result->items as $key => $user) {
                $agentID = $user->id;
            }
        }
        
        return $agentID;
    }

}

app/Http/Controllers/Agent/HomeAgentController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Illuminate\Http\Request;

class HomeAgentController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('agent');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('agent.agent-home');
    }
}

resources/views/agent/partials/head-agent.blade.php
<meta charset="utf-8">
<title>
    Agent Portal
</title>

<meta http-equiv="X-UA-Compatible"
      content="IE=edge">
<meta content="width=device-width, initial-scale=1.0"
      name="viewport"/>
<meta http-equiv="Content-type"
      content="text/html; charset=utf-8">

<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<link href="{{ url('adminlte/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet"
      href="{{ url('adminlte/css') }}/select2.min.css"/>
<link href="{{ url('adminlte/css/AdminLTE.min.css') }}" rel="stylesheet">
<link href="{{ url('adminlte/css/skins/skin-blue.min.css') }}" rel="stylesheet">
<link rel="stylesheet"
      href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.standalone.min.css"/>
<link rel="stylesheet" href="{{ asset('css/app.css') }}"/>
<link href="{{ asset('assets/vendors/fancybox/source/jquery.fancybox.css') }}" rel="stylesheet" type="text/css" />
@yield('header_styles')

resources/views/agent/partials/header-agent.blade.php
<div class="page-header-inner">
    <div class="page-header-inner">
        <div class="navbar-header">
            <a href="{{ url('/admin/home') }}"
               class="navbar-brand">
                @trans('global.global_title')
            </a>
        </div>
        <a href="javascript:;"
           class="menu-toggler responsive-toggler"
           data-toggle="collapse"
           data-target=".navbar-collapse">
        </a>

        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">

            </ul>
        </div>
    </div>
</div>

resources/views/agent/partials/javascripts-agent.blade.php
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="{{ url('adminlte/js') }}/bootstrap.min.js"></script>
<script src="{{ url('adminlte/js') }}/select2.full.min.js"></script>
<script src="{{ url('adminlte/js') }}/main.js"></script>

<script src="{{ url('adminlte/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url('adminlte/plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url('adminlte/js/app.min.js') }}"></script>
<script src="{{ url('js/app_extra.js') }}"></script>

{{-- Fancybox --}}
<script src="{{ asset('assets/vendors/fancybox/source/jquery.fancybox.js') }}" type="text/javascript"></script>
<script>
    window._token = '{{ csrf_token() }}';
</script>
<script>
    $(function(){
        // Enables popover
        $("[data-toggle=popover]").popover();
    });
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.fancyboxprofile').fancybox();
    });
</script>

@yield('javascript')

resources/views/agent/partials/sidebar-agent.blade.php
@inject('request', 'Illuminate\Http\Request')
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <ul class="sidebar-menu">

            <li class="{{ $request->segment(2) == 'home' ? 'active' : '' }}">
                <a href="{{ url('/agent/home') }}">
                    <i class="fa fa-tachometer"></i>
                    <span class="title">@lang('global.app_dashboard')</span>
                </a>
            </li>
			<li class="treeview">
                <a href="#">
                    <i class="fa fa-bar-chart-o"></i>
                    <span class="title">Reports</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    <li class="{{ $request->segment(1) == 'agent' && $request->segment(2) == 'report' ? 'active active-sub' : '' }}">
                        <a href="{{ route('agent.report') }}">
                            <i class="fa  fa-list-alt"></i>
                            <span class="title">
                                Agent Reports
                            </span>
                        </a>
                    </li>
                    <li class="{{ $request->segment(1) == 'agent2' ? 'active active-sub' : '' }}">
                        <a href="{{ route('agent2.report') }}">
                            <i class="fa  fa-list-alt"></i>
                            <span class="title">
                                Agent Reports 2
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
			
            <li>
                <a href="{{ route('agent.post-logout') }}">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">@lang('global.app_logout')</span>
                </a>
            </li>
        </ul>
    </section>
</aside>

resources/views/agent/partials/topbar-agent.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ url('/admin/home') }}" class="logo"
       style="font-size: 16px;">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">
           @lang('global.global_title')</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">
           @lang('global.global_title')</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-right" style="margin-right:-5px">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        
                        <!-- Notifications: style can be found in dropdown.less -->
                        
                        <!-- Tasks: style can be found in dropdown.less -->
                        
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span>{{ Session::has('AgentName') ? Session::get('AgentName') : '' }}<i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{ route('agent.post-logout') }}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

    </nav>
</header>