routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

//New Password From Direct Login Luma account
//$this->get('login/password/directlogin/new', 'Auth\DirectLoginController@showDirectLoginPasswordForm')->name('directlogin.password');
Route::post('directlogin/account/new', ['uses' => 'Auth\DirectLoginController@createAccount', 'as' => 'directlogin.password']);

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    
});

/*
** AirAsia Orders
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'airasia', 'as' => 'aa_orders.'], function () {
   Route::get('/orders',['as'=>'index','uses'=>'Admin\Reports\AirasiaOrderController@index']);
   Route::get('/orders/{id}/paxslip',['as'=>'orders.paxslip','uses'=>'Admin\Reports\AirasiaOrderController@paxSlip']);
   Route::post('orders/upload',['uses'=>'Admin\Reports\AirasiaOrderController@upload']);
});

/*
** Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'report', 'as' => 'report.'], function () {
        Route::get('warehouse',['as'=> 'warehouse', 'uses' => 'Admin\Reports\WarehouseReportsController@index']);
        Route::get('warehouse/export',['as'=> 'export', 'uses' => 'Admin\Reports\WarehouseReportsController@exportReportCSV']);
        Route::get('warehouse/order/{id}',['as'=> 'warehouse.detail', 'uses' => 'Admin\Reports\WarehouseReportsController@orderDetail']);
        Route::get('warehouse/order/{id}/paxslip',['as'=> 'warehouse.paxslip', 'uses' => 'Admin\Reports\WarehouseReportsController@paxSlip']);

        Route::post('warehouse/order/update/{id}',['as' => 'warehouse.update-status', 'uses' => 'Admin\Reports\WarehouseReportsController@updateStatus']);
    });

/*
** New Warehouse Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'wreport2', 'as' => 'wreport2.'], function () {

   Route::get('warehouse2',['as'=> 'warehouse', 'uses' => 'Admin\Reports\WarehouseReports2Controller@index']);
   Route::get('warehouse2/export',['as'=> 'export', 'uses' => 'Admin\Reports\WarehouseReports2Controller@exportReport']);
   Route::get('warehouse2/order/{seller_id}/view/{order_id}',['as'=> 'warehouse.detail', 'uses' => 'Admin\Reports\WarehouseReports2Controller@orderDetail']);
   Route::get('warehouse2/order/{seller_id}/paxslip/{order_id}',['as'=> 'warehouse.paxslip', 'uses' => 'Admin\Reports\WarehouseReports2Controller@paxSlip']);
   Route::post('warehouse2/order/{order_id}/updatemagento/{seller_ids}',['as' => 'warehouse.magento-order-update-status', 'uses' => 'Admin\Reports\WarehouseReports2Controller@updateAdminStatus']);
   Route::post('warehouse2/order/{order_id}/updateseller/{seller_id}',['as' => 'warehouse.seller-order-update-status', 'uses' => 'Admin\Reports\WarehouseReports2Controller@updateSellerOrderStatus']);
   Route::get('warehouse2/order/{seller_id}/invoice/{increment_id}/{order_id}',['as'=> 'warehouse.invoice', 'uses' => 'Admin\Reports\WarehouseReports2Controller@generateInvoice']);


});

/*
** Custom Report
*/
Route::group(['middleware' => ['auth'], 'prefix' => 'customreport', 'as' => 'customreport.'], function () {
   Route::get('/',['as'=> 'index', 'uses' => 'Admin\Reports\CustomReportController@index']);
   Route::get('/exportall',['as'=> 'exportAll', 'uses' => 'Admin\Reports\CustomReportController@exportAllCustomReports']);
   Route::get('/order/export',['as'=> 'export', 'uses' => 'Admin\Reports\CustomReportController@exportCustomReportExcel']);
   Route::get('/order/{id}',['as'=> 'detail', 'uses' => 'Admin\Reports\CustomReportController@orderDetail']);
   Route::get('/order/{id}/paxslip',['as'=> 'paxslip', 'uses' => 'Admin\Reports\CustomReportController@paxSlip']);
   Route::post('/order/update/{id}',['as' => 'update-status', 'uses' => 'Admin\Reports\CustomReportController@updateStatus']);

});


//Seller Portal

// Change Password Routes...
$this->get('seller/change_password', 'Seller\Auth\ChangePasswordController@showChangePasswordForm')->name('seller-change_password');
$this->patch('seller/change_password', 'Seller\Auth\ChangePasswordController@changePassword')->name('seller.change_password');

// Password Reset Routes...
$this->get('seller/password/reset', 'Seller\Auth\ForgotPasswordController@showLinkRequestForm')->name('seller-password-reset-link');
$this->post('seller/password/email', 'Seller\Auth\ForgotPasswordController@sendResetLinkEmail')->name('seller-password-reset-email');
$this->get('seller/password/reset/{token}', 'Seller\Auth\ResetPasswordController@showResetForm')->name('password-reset-form');
$this->post('seller/password/reset', 'Seller\Auth\ResetPasswordController@reset')->name('seller-password-reset');

$this->post('seller/logout', 'Seller\Auth\SellerLoginController@logout')->name('seller.post-logout');
$this->get('seller/login', 'Seller\Auth\SellerLoginController@showLoginForm')->name('seller.login');;
$this->post('seller/login','Seller\Auth\SellerLoginController@login')->name('seller.post-login');

Route::group(['middleware' => ['seller'], 'prefix' => 'seller', 'as' => 'seller.'], function () {
    
   
    Route::get('/',['as' => 'index','uses' => 'Seller\Auth\HomeSellerController@index']);
    Route::get('/home',['as' => 'home','uses' => 'Seller\Auth\HomeSellerController@index']);
   
    Route::get('/orders',['as'=> 'orders-index', 'uses' => 'Seller\Reports\SellerSalesReportController@index']);
    Route::get('/order/{orderid}/{sellerid}',['as'=> 'order-detail', 'uses' => 'Seller\Reports\SellerSalesReportController@orderDetail']);

    Route::post('/order/{orderid}/{sellerid}/status/{status}',['as'=> 'update-order-status', 'uses' => 'Seller\Reports\SellerSalesReportController@updateOrderStatus']);
    Route::post('/order/itemstatus',['as'=> 'update-item-status', 'uses' => 'Seller\Reports\SellerSalesReportController@updateItemStatus']);
    Route::get('/sellerorders/export',['as'=> 'export', 'uses' => 'Seller\Reports\SellerSalesReportController@exportReport']);
    
    Route::resource('permissions', 'Seller\AccountManagement\SellerPermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerPermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Seller\AccountManagement\SellerRolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerRolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Seller\AccountManagement\SellerUsersController');
    Route::post('users_mass_destroy', ['uses' => 'Seller\AccountManagement\SellerUsersController@massDestroy', 'as' => 'users.mass_destroy']);

});

/*
** Agent
*/
Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::get('login',['as' => 'login','uses' => 'Agent\AgentLoginController@showLoginForm']);
    Route::post('login',['as' => 'post-login','uses' => 'Agent\AgentLoginController@agentLogin']);
    Route::get('logout',['as' => 'post-logout','uses' => 'Agent\AgentLoginController@agentLogout']);
});
Route::group(['middleware' => ['agent'],'prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::get('/home', 'Agent\HomeAgentController@index');
    Route::get('report',['as'=> 'report', 'uses' => 'Agent\AgentReportsController@index']);
    Route::get('report/export',['as'=> 'export', 'uses' => 'Agent\AgentReportsController@exportReportCSV']);
    Route::get('report/order/{id}',['as'=> 'report.detail', 'uses' => 'Agent\AgentReportsController@orderDetail']);
    Route::get('report/order/{id}/paxslip',['as'=> 'report.paxslip', 'uses' => 'Agent\AgentReportsController@paxSlip']);

    Route::get('choose-update','Agent\AgentReportsController@getChooseUpdate');
    Route::get('change-pnr/{pnr}','Agent\AgentReportsController@getChangePnr');
    Route::get('change-flight/{pnr}','Agent\AgentReportsController@getFlight');
    Route::get('change-pax','Agent\AgentReportsController@getChangePax');
    Route::get('change-status','Agent\AgentReportsController@getChangeStatus');
    Route::get('/agentid','Agent\UserAgentController@index');
    Route::get('report/order/{id}',['as'=> 'report.detail', 'uses' => 'Agent\AgentReportsController@orderDetail']);
    Route::get('report/pnr/{pnr}',['as'=> 'report.pnr', 'uses' => 'Agent\AgentReportsController@apiGetBooking']);

app/AirasiaOrder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\ModelNotFoundException;

use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;


class AirasiaOrder extends Model
{


	protected $fillable = [
	                    'file_id',
						'purchase_date',
						'pnr',
						'flight_number',
						'currency_code',
						'item_code',
						'item_description',
						'quantity',
						'charge_amount',
						'departure_date',
						'email_address',
						'carrier_code',
						'first_name',
						'last_name',
						'amount_in_myr'
					];
    

	public function savedata($file_id,$sheetData)
	{

        foreach ($sheetData as $key => $value) {
			
			//remove the milliseconds 2018-02-07 10:32:15.820000000
      		$filtered_purchasedate = substr($value['purchasedate'], 0, strpos($value['purchasedate'], "."));
            $purchasedate = date('Y-m-d H:i:s',strtotime($filtered_purchasedate));

            $departuredate = date('Y-m-d H:i:s',strtotime($value['departuredate']));

		        parent::Create([
		        		'file_id' => $file_id,
						'purchase_date' => $purchasedate,
						'pnr' => $value['pnr'],
						'flight_number' => $value['flightnumber'],
						'currency_code' => $value['currencycode'],
						'item_code' => $value['itemcode'],
						'item_description' => $value['itemdescription'],
						'quantity' => $value['quantity'],
						'charge_amount' => $value['chargeamount'],
						'departure_date' => $departuredate,
						'email_address' => $value['emailaddress'],
						'carrier_code' => $value['carriercode'],
						'first_name' => $value['firstname'],
						'last_name' => $value['lastname'],
						'amount_in_myr' => $value['amountinmyr']
					]);
        }
	}

	public function search($searchFields,$sortField,$sortDirection)
	{
	
		$queryBlock = "";

		if(isset($searchFields['flight_date']))
		{

			$queryBlock .= "("."DATE(departure_date) >= " .
                        "STR_TO_DATE('" . addslashes($searchFields['flight_date']['from']) . "','%m/%d/%Y')" . " AND " . "DATE(departure_date) <= ".
                        "STR_TO_DATE('" . addslashes($searchFields['flight_date']['to']) . "','%m/%d/%Y')" . ")";

		}

		if(isset($searchFields['sales_date']))
		{
			if(isset($searchFields['flight_date']))
			{
				$queryBlock .= " AND ";
			}

			$queryBlock .= "("." DATE(purchase_date) >= " . "STR_TO_DATE('" . addslashes($searchFields['sales_date']['from']) . "','%m/%d/%Y')".
                           " AND "."DATE(purchase_date) <= " . "STR_TO_DATE('" . addslashes($searchFields['sales_date']['to']) . "','%m/%d/%Y')" . ")";
			
		}
         
        $filter_results = parent::select('*')->whereRaw($queryBlock)->orderBy($sortField,$sortDirection)->paginate(10);
        return $filter_results;

	}

    public function getOrderDetails($order_id)
    {
        $order_detail = parent::select('*')->where('id',$order_id)->get();
        return $order_detail;
    }
}

resources/views/admin/report/airasia_orders/index-orders.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

{{-- page level styles --}}
@section('header_styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}" />
    {{--<link href="{{ asset('css/tables.css') }}" rel="stylesheet" type="text/css" />--}}
    <link href="{{ asset('assets/vendors/sweetalert/css/sweetalert.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/vendors/daterangepicker/css/daterangepicker.css') }}" rel="stylesheet" type="text/css" />
@stop

@section('content')
<section class="content paddingleft_right15">
    <div class="row">
            <div class="panel panel-primary ">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left"> <i class="livicon" data-name="sitemap" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    AirAsia Orders
                </h4>
            </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-4 pull-right">
                            <h4>File Upload</h4>
                            <form method="POST" role="form" action="orders/upload" enctype="multipart/form-data">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="file" class="form-control-file" style="width:230px;display:inline-block;" name="spreadsheet[]" accept=".csv" multiple>
                                    <input type="submit" value="upload" style="margin-top:-5px;display:inline-block;" class="btn btn-success btn-sm">
                            </form>
                        </div>
                    </div>
                    <div class="row">
                    @include('admin.report.airasia_orders.partials.filter') 
                    </div>
                    <div class="row">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover sortable dataTable" id="table">
                                <thead>
                                    <tr>
                                        <th data-sort="DESC" data-sortby="purchase_date" class="sort {{ $css_sort_purchase_date }}" data-class="{{ $css_sort_purchase_date }}">Purchase Date</th>
                                        <th data-sort="DESC" data-sortby="pnr" class="sort {{ $css_sort_pnr }}" data-class="{{ $css_sort_pnr }}">PNR</th>
                                        <th data-sort="DESC" data-sortby="flight_number" class="sort {{ $css_sort_flight_number }}" data-class="{{ $css_sort_flight_number }}">Flight Number</th>
                                        <th data-sort="DESC" data-sortby="currency_code" class="sort {{ $css_sort_currency_code }}" data-class="{{ $css_sort_currency_code }}">Currency Code</th>
                                        <th data-sort="DESC" data-sortby="item_code" class="sort {{ $css_sort_item_code }}" data-class="{{ $css_sort_item_code }}">Item Code</th>
                                        <th data-sort="DESC" data-sortby="item_description" class="sort {{ $css_sort_item_description }}" data-class="{{ $css_sort_item_description }}">Item Description</th>
                                        <th data-sort="DESC" data-sortby="quantity" class="sort {{ $css_sort_quantity }}" data-class="{{ $css_sort_quantity }}">Quantity</th>
                                        <th data-sort="DESC" data-sortby="charge_amount" class="sort {{ $css_sort_charge_amount }}" data-class="{{ $css_sort_charge_amount }}">Charge Amount</th>
                                        <th data-sort="DESC" data-sortby="departure_date" class="sort {{ $css_sort_departure_date }}" data-class="{{ $css_sort_departure_date }}">Departure Date</th>
                                        <th data-sort="DESC" data-sortby="email_address" class="sort {{ $css_sort_email_address }}" data-class="{{ $css_sort_email_address }}">Email Address</th>
                                        <th data-sort="DESC" data-sortby="carrier_code" class="sort {{ $css_sort_carrier_code }}" data-class="{{ $css_sort_carrier_code }}">Carrier Code</th>
                                        <th data-sort="DESC" data-sortby="first_name" class="sort {{ $css_sort_first_name }}" data-class="{{ $css_sort_first_name }}">First Name</th>
                                        <th data-sort="DESC" data-sortby="last_name" class="sort {{ $css_sort_last_name }}" data-class="{{ $css_sort_last_name }}">Last Name</th>
                                        <th data-sort="DESC" data-sortby="amount_in_myr" class="sort {{ $css_sort_amount_in_myr }}" data-class="{{ $css_sort_amount_in_myr }}">Amount in MYR</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($sheet_records as $row )
                                    <tr>
                                        <td>{{ date('m-d-Y',strtotime($row->purchase_date)) }}</td>
                                        <td>{{ $row->pnr }}</td>
                                        <td>{{ $row->flight_number }}</td>
                                        <td>{{ $row->currency_code }}</td>
                                        <td>{{ $row->item_code }}</td>
                                        <td>{{ $row->item_description }}</td>
                                        <td>{{ $row->quantity }}</td>
                                        <td>{{ $row->charge_amount }}</td>
                                        <td>{{ date('m-d-Y',strtotime($row->departure_date)) }}</td>
                                        <td>{{ $row->email_address }}</td>
                                        <td>{{ $row->carrier_code }}</td>
                                        <td>{{ $row->first_name }}</td>
                                        <td>{{ $row->last_name }}</td>
                                        <td>{{ $row->amount_in_myr }}</td>
                                        <td><a class="btn btn-primary" target="_blank" href="{{ route('aa_orders.orders.paxslip',$row->id) }}" data-toggle="tooltip" data-placement="top" data-title="Print Packing Slip" ><i class="fa fa-print"></i></a></td>
                                    </tr>
                                @endforeach     
                                </tbody>
                            </table>
                        </div>
                        <div class="row">

                        <div class="col-md-12 text-right">
                            <!--{{ $sheet_records->render() }}-->
                            {{ $links }}
                        </div>
                    </div>   
                </div>
            </div>
        </div>       
    </div>
</div>
    
       
@endsection
{{-- page level scripts --}}
@section('javascript')
    <script src="{{ asset('assets/vendors/sweetalert/js/sweetalert.min.js') }}" type="text/javascript"></script>
    {{--<script src="{{ asset('assets/vendors/sweetalert/js/sweetalert-dev.js') }}" type="text/javascript"></script>--}}
    {{--<script src="{{ asset('assets/js/pages/custom_sweetalert.js') }}" type="text/javascript"></script>--}}
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/daterangepicker/js/moment.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/daterangepicker/js/daterangepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/airasia_orders.js') }}"></script>
    @include('layouts.flash')
@stop

resources/views/admin/report/airasia_orders/paxslip-print.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<head>
	<title>Air Asia Order - Pax Slip</title>
</head>
<style>
                html{
                    font-family: 'Gotham Rounded', sans-serif;
                    font-size: 13px;
                    font-weight: 400;
                    color: #555;
                    height: 100%;
                    width: 100%!important;
                    margin: 0;
                    padding: 0;
                }
                .page-header{
                    font-size: 1.7em;
                    font-weight: 700;
                    padding: 10px 0;
                    margin: 0;
                    color: #dc2118;
                    text-transform: uppercase;
                    letter-spacing: -1px;
                    border-bottom: 8px solid #f1f1f1;
                }

                .pnr{
                    font-size: 0.75em;
                }

                .invoice-block{
                    padding: 15px;
                }

                .well{
                    margin-top:30px;
                }

                .flight-details, .details{
                    
                }

                .flight-details{
                    text-transform: uppercase;
                    color: #999;
                    font-weight: 700;
                    font-size: 1.5em;
                    top: 0;
                    left: 15px;
                }

                .details{

                }

                                
                .table-relative{
                    margin: 140px -15px 0px;
                    border-top: 1px solid #cbd2b0;
                    border-bottom: 1px solid #cbd2b0;
                    padding: 20px 15px 0px;
                    
                }

                .pre{
                    font-family: 'Gotham Rounded', sans-serif;
                    font-weight: 700;
                    line-height: 1em;
                    text-shadow: 0 0 1px rgba(51,51,51,.2);
                    color: inherit;
                }

                .table{
                    border-collapse: collapse;
                    border-spacing: 0;
                    background: #fff;
                    margin: 10px 0;
                }

                tr:nth-child(odd) {background-color: #f9f9f9;}

                .table > tbody{
                    border-bottom: 5px solid #cbd2b0;
                }
                    
                .table > thead > tr > th {
                    background: #DDD;
                    color: #000;
                    font-size: 12px;
                    letter-spacing: 1px;
                    text-transform: uppercase;
                    font-weight: 700;
                    padding: 12px 5px;
                    border: none;
                    text-align: left;
                }

                .table > tbody > tr > td{
                    padding-left:5px;
                    height: 55px;
                    font-size:13px;
                    
                }
                tr:not(:first-child) {
                    border-top: 1px solid #ddd;
                }

                .product-num, .name{
                    display:inline;
                }
                .row{
                    width: 100%;
                }
                .col1{
                    float: left;
                    width: 50%;
                }
                @media screen{
                    .product-num{
                        background: #333333;
                        font-size: 12px;
                        padding: 7px;
                        width: 20px;
                        text-align: center;
                        border-radius: 35px;
                        color: #fff;
                        font-weight: 700;
                        position:absolute;
                        margin-top: -7px;
                    }

                    .name{
                        padding-left: 25%;
                    }
                }
</style>
<body>
    <div class="inner-spacer print_area">
        @if($order_result)
        @foreach($order_result as $key => $order)
        <div class="invoice-block" style="border:1px dashed black;">
            <div class="page-header">
                <div class="pnr">PNR :  {{ $order->pnr }}</div>
            </div>
            <div class="well">
                <div class="row">
                    <div class="col1">
                        <div class="flight-details">Flight Details</div>
                        <div class="details">
                            <strong><span style="width: 100px; float: left;">Carrier Code </span>: {{ $order->carrier_code }}</strong><br>
                            <strong><span style="width: 100px; float: left;">Flight Number </span>: {{ $order->flight_number }}</strong><br>
                            <strong><span style="width: 100px; float: left;">Flight Date </span>: {{ date('Y-m-d',strtotime($order->departure_date)) }}</strong><br>
                        </div>
                    </div>
                    <div class="col1">
                        <div class="flight-details">Passenger Details</div>
                        <div class="details">
                            <strong><span style="width: 100px; float: left;">Name </span>: {{ $order->first_name }} {{ $order->last_name }}</strong><br>
                            <strong><span style="width: 100px; float: left;">Seat No </span>: {{ $order->seat_number }}</strong><br>
                        </div>
                    </div>                       
                </div>
            </div>
            <div class="table-relative">
                <span class="pre">ITEMS</span>
                <table class="table table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th width="10%">SI. No.</th>
                            <th width="10%">SKU</th>
                            <th width="30%">Description</th>
                            <th width="10%">Quantity</th>
                            <th width="10%">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                    	<!--foreach($order->items as $itemkey => $item)
                        php
                        $price = $item->price_per_item;
                        $qty = number_format($item->qty,0);
                        endphp--> 
				        <tr>
				            <td>
				                <div class="product-name">
				                    <div class="product-num">1</div>
				                </div>
				            </td>
				            <td> {{ $order->item_code }} </td>
				            <td> {{ $order->item_description }} </td>
				            <td> {{ $order->quantity }} </td>
				            <td> {{ number_format(($order->amount_in_myr * $order->quantity),2) }} </td>
				        </tr>
				        <!--endforeach-->
					</tbody>
				</table>
	            <div class="row">
	                <div class="col-lg-12 remittance">
	                </div>
	            </div>
            	<div class="alert alert-danger alert-inbox" style="display: none; position: absolute; top: 40%;"></div>
            	<div class="loader-darkener"></div>
            	<div class="fa-spin dummy-loader"></div>
	            <div class="alert alert-danger alert-inbox" style="display: none; position: absolute; top: 40%;"></div>
	            <div class="loader-darkener"></div>
	            <div class="fa-spin dummy-loader"></div>
            </div>
    	</div>
    	@endforeach
        @endif
	</div>
</body>
</html>